spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      batch-size: 16384

sensor.simulator.sensor-type-configs:
    - sensor-type: "HEART_RATE_MONITOR"
      sensor-id-prefix: "hm"
      num-sensors: 20
      min-value: 50
      max-value: 150
      topic: "sensor-readings"
      group-ids:
        - "fitness"
        - "medical"

    - sensor-type: "THERMOSTAT"
      sensor-id-prefix: "therm"
      num-sensors: 20
      min-value: 10
      max-value: 35
      topic: "sensor-readings"
      group-ids:
        - "home"
        - "work"
    - sensor-type: "FUEL_GAUGE"
      sensor-id-prefix: "fg"
      num-sensors: 20
      min-value: 0
      max-value: 100
      topic: "sensor-readings"
      group-ids:
        - "home"
        - "work"

logging:
  level:
    root: INFO
    com.iot.simulator: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
